import "./styles/globals.css"
import { HeroUIProvider } from "@heroui/react";
import Footer from "@/components/footer";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <HeroUIProvider>
          {children}
          <Footer />
        </HeroUIProvider>
      </body>
    </html>
  );
}